### ISSUE TITLE
Is the radio playback working?

### ISSUE THREAD

**Issue by Xalip** [cristianpb/snipshandler#6]
Hi,

I've seen your repo and asked myself whether the radio stream is working. Are you playing the radio on the same host as rhasspy (so the hardware which is running rhasspy is a snapcast client as well)?

Thanks

**Comment by cristianpb** [comment]
Hi @Xalip 

Thanks for you issue and sorry about the late response, I didn't receive any notification.

Yes, I have rhasspy, mopidy, snapcastserver and a snapcastclient in the same host.

Using only alsa one can have both using this configuration https://community.rhasspy.org/t/stream-music-or-radio/497/27
If not you can only have audio either for snapcast or from rhasspy (aplay)

I will close the issue if it's OK for you.

**Comment by Xalip** [comment]
@cristianpb thanks for your response. Well Bozor is me in the rhasspy community so I figured it out. Thanks anyway
